export let ghosts = [
  { name: "Spirit", id: 1, evidences: [1,3,6], Str: "nothing", Weak: "Smudge" },
  { name: "Wraith", id: 2, evidences: [1,3,7], Str: "No footprints, Sees through doors", Weak: "Salt" },
  { name: "Phantom", id: 3, evidences: [3,5,7], Str: "Lowers sanity", Weak: "Photo" },
  { name: "Poltergeist", id: 4, evidences: [3,5,6], Str: "Throws stuff", Weak: "Empty rooms" },
  { name: "Banshee", id: 5, evidences: [2,5,7], Str: "Picks one target", Weak: "Crucifix" },
  { name: "Jinn", id: 6, evidences: [1,4,5], Str: "Longer distance -> faster", Weak: "Turn off power" },
  { name: "Mare", id: 7, evidences: [2,3,6], Str: "Darkness", Weak: "Lights" },
  { name: "Revenant", id: 8, evidences: [2,4,6], Str: "Fast boi", Weak: "Hide behind a palm tree" },
  { name: "Shade", id: 9, evidences: [1,4,6], Str: "Shy, hard to find", Weak: "Multiple players nearby" },
  { name: "Demon", id: 10, evidences: [4,5,6], Str: "Attacks often", Weak: "Ouija Board ANSWERS won't lower sanity" },
  { name: "Yurei", id: 11, evidences: [2,4,7], Str: "Drains sanity", Weak: "Smudging stops it from wandering around" },
  { name: "Oni", id: 12, evidences: [1,4,7], Str: "Active when near players", Weak: "Easier to find and identify" },
  // { name: "Unicel", id: 13, evidences: [], Str: "nothing", Weak: "Smudge" },
  { name: "Goryo", id: 13, evidences: [1,5,7], Str: "DOTS only through camera when no players around", Weak: "Doesn't wander far" },
  { name: "Hantu", id: 14, evidences: [2,4,5], Str: "Faster in low temperatures", Weak: "Slower in warmer areas" },
  { name: "Myling", id: 15, evidences: [1,5,6], Str: "Quieter footsteps", Weak: "Causes paranormal sounds often" },
  { name: "Obake", id: 16, evidences: [1,2,5], Str: "Rarely leaves traces from interactions", Weak: "Sometimes leaves unique evidence" },
  { name: "Onryo", id: 17, evidences: [2,3,4], Str: "Extinguishing a flame might cause a hunt", Weak: "Less likely to hunt when threatened" },
  { name: "Raiju", id: 18, evidences: [1,2,7], Str: "Faster near electrical devices", Weak: "Distrupts electronics" },
  { name: "Twins", id: 19, evidences: [1,3,4], Str: "Both twins can hunt", Weak: "Often two interactions at the same time" },
  { name: "Yokai", id: 20, evidences: [2,3,7], Str: "Talking near it may cause hunt", Weak: "Limited hearing during hunt" },
  { name: "Mimic", id: 21, evidences: [3,4,5], Str: "Copies other ghosts", Weak: "Orbs follow it"},
  { name: "Deogen", id: 22, evidences: [3,6,7], Str: "Knows your location", Weak: "Slow when near the player"},
  { name: "Moroi", id: 23, evidences: [3,4,6], Str: "Faster at low player sanity", Weak: "Blind from smudging lasts longer"},
  { name: "Thaye", id: 24, evidences: [2,6,7], Str: "Active in the beginning", Weak: "Becomes quieter and slower"},
]

export let evidences = [
  { name: "EMF Level 5", id: 1 },
  { name: "Ghost Orb", id: 2 },
  { name: "Spirit Box", id: 3 },
  { name: "Freezing Temperatures", id: 4 },
  { name: "Fingerprints", id: 5 },
  { name: "Ghost Writing", id: 6 },
  { name: "D.O.T.S Projector", id: 7},
]